export const catalogDefinitions = {
  companies: {
    table: "companies",
    autoCode: { field: "code", prefix: "EMP-" },
    permission: "catalogs",
    label: "Empresa",
    select: `SELECT id, code, legal_name, trade_name, tax_id, is_active, created_at, updated_at FROM companies ORDER BY legal_name`,
    fields: {
      code: { type: "code", required: true, max: 30 },
      legal_name: { type: "text", required: true, max: 180 },
      trade_name: { type: "text", max: 180, default: "" },
      tax_id: { type: "text", max: 30, default: "" },
      is_active: { type: "boolean", default: 1 },
    },
  },
  branches: {
    table: "branches",
    autoCode: { field: "code", prefix: "SUC-" },
    permission: "catalogs",
    label: "Sucursal",
    select: `SELECT b.id, b.company_id, b.code, b.name, b.address, b.timezone, b.is_active, b.created_at, b.updated_at, c.legal_name AS company_name FROM branches b JOIN companies c ON c.id = b.company_id ORDER BY b.name`,
    fields: {
      company_id: { type: "id", required: true },
      code: { type: "code", required: true, max: 30 },
      name: { type: "text", required: true, max: 150 },
      address: { type: "text", max: 500, default: "" },
      timezone: { type: "text", required: true, max: 80, default: "America/Chicago" },
      is_active: { type: "boolean", default: 1 },
    },
  },
  areas: {
    table: "areas",
    autoCode: { field: "code", prefix: "ARE-" },
    permission: "catalogs",
    label: "Área",
    select: `SELECT a.id, a.code, a.name, a.description, a.is_active, a.created_at, a.updated_at, COUNT(ua.user_id) AS users_count FROM areas a LEFT JOIN user_areas ua ON ua.area_id = a.id GROUP BY a.id ORDER BY a.name`,
    fields: {
      code: { type: "code", required: true, max: 30 },
      name: { type: "text", required: true, max: 120 },
      description: { type: "text", max: 500, default: "" },
      is_active: { type: "boolean", default: 1 },
    },
  },
  warehouses: {
    table: "warehouses",
    autoCode: { field: "code", prefix: "ALM-" },
    permission: "catalogs",
    label: "Almacén",
    select: `SELECT w.id, w.branch_id, w.code, w.name, w.description, w.is_active, w.created_at, w.updated_at, b.name AS branch_name FROM warehouses w JOIN branches b ON b.id = w.branch_id ORDER BY w.name`,
    fields: {
      branch_id: { type: "id", required: true },
      code: { type: "code", required: true, max: 30 },
      name: { type: "text", required: true, max: 150 },
      description: { type: "text", max: 500, default: "" },
      is_active: { type: "boolean", default: 1 },
    },
  },
  units: {
    table: "units_of_measure",
    permission: "catalogs",
    label: "Unidad de medida",
    select: `SELECT id, code, name, symbol, decimals, is_active, created_at, updated_at FROM units_of_measure ORDER BY name`,
    fields: {
      code: { type: "code", required: true, max: 20 },
      name: { type: "text", required: true, max: 100 },
      symbol: { type: "text", required: true, max: 20 },
      decimals: { type: "integer", required: true, min: 0, maxValue: 6, default: 2 },
      is_active: { type: "boolean", default: 1 },
    },
  },
  currencies: {
    table: "currencies",
    permission: "catalogs",
    label: "Moneda",
    select: `SELECT id, code, name, symbol, exchange_rate, is_base, is_active, created_at, updated_at FROM currencies ORDER BY is_base DESC, code`,
    fields: {
      code: { type: "code", required: true, max: 3 },
      name: { type: "text", required: true, max: 100 },
      symbol: { type: "text", required: true, max: 10 },
      exchange_rate: { type: "number", required: true, min: 0.000001, default: 1 },
      is_base: { type: "boolean", default: 0 },
      is_active: { type: "boolean", default: 1 },
    },
  },
  document_states: {
    table: "document_states",
    permission: "catalogs",
    label: "Estado de documento",
    select: `SELECT id, code, name, description, color, sequence, is_terminal, is_active, created_at, updated_at FROM document_states ORDER BY sequence, name`,
    fields: {
      code: { type: "code", required: true, max: 40 },
      name: { type: "text", required: true, max: 100 },
      description: { type: "text", max: 500, default: "" },
      color: { type: "color", required: true, default: "#68736d" },
      sequence: { type: "integer", required: true, min: 0, maxValue: 9999, default: 0 },
      is_terminal: { type: "boolean", default: 0 },
      is_active: { type: "boolean", default: 1 },
    },
  },
};
